import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  bottomSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    overflow: "hidden",
  },
  sheetContent: {
    paddingTop: 10,
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  handle: {
    alignSelf: "center",
    width: 56,
    height: 6,
    borderRadius: 3,
    marginBottom: 16,
  },
  footerSpacer: {
    width: "100%",
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#4A363A",
    marginBottom: 16,
  },
  contentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  contentRowLocked: {
    opacity: 0.55,
  },
  contentId: {
    width: 38,
    fontSize: 24,
    fontWeight: "700",
    color: "#5E6A7E",
    marginRight: 10,
    textAlign: "center",
  },
  contentBody: {
    flex: 1,
    paddingRight: 10,
  },
  contentDuration: {
    fontSize: 14,
    color: "#5E6A7E",
    marginBottom: 4,
  },
  contentTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#3D2C34",
    marginBottom: 8,
  },
  typePill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EAF2F8",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  typeIcon: {
    marginRight: 5,
  },
  typePillText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#496074",
  },
  playButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#E7F1F8",
    alignItems: "center",
    justifyContent: "center",
  },
  playButtonViewed: {
    backgroundColor: "#DFF0FC",
    borderWidth: 1,
    borderColor: "#8BBEE4",
  },
  lockNotice: {
    backgroundColor: "#F4EBDD",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 14,
  },
  lockNoticeText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#73470A",
  },
  actionBarContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    paddingTop: 15,
    paddingBottom: 15,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 30,
  },
  cartButton: {
    width: 84,
    height: 62,
    borderRadius: 31,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  buyNowButton: {
    flex: 1,
    height: 62,
    borderRadius: 31,
    alignItems: "center",
    justifyContent: "center",
  },
  buyNowText: {
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  buyNowContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  buyNowIcon: {
    marginRight: 6,
  },
});
